SELECT SUM(SAL)
      ,AVG(SAL)
FROM EMP
;

SELECT DISTINCT DEPTNO
FROM EMP
;

SELECT DISTINCT DEPTNO, SAL
FROM EMP
;

SELECT SUM(DISTINCT SAL) AS SUM_OF_DISTINCT
      ,SUM(SAL) AS SUM_OF_ALL 
FROM EMP
;

SELECT MAX(SAL),
       MIN(SAL),
       ROUND(MAX(SAL)/MIN(SAL),1) 
FROM EMP
WHERE DEPTNO = 10
;

SELECT COUNT(EMPNO)
      ,COUNT(COMM)
FROM EMP
;

SELECT COUNT(*)
FROM EMP
WHERE DEPTNO = 30
;

SELECT COUNT(DISTINCT SAL)
      ,COUNT(SAL)
FROM EMP
;

SELECT COUNT(ENAME)
FROM EMP
WHERE NVL(COMM,0) >0
;

SELECT AVG(SAL)
      ,'10' AS DNO
FROM EMP
WHERE DEPTNO =10
;

SELECT AVG(SAL)
      ,'10' AS DNO
FROM EMP
WHERE DEPTNO =10
UNION ALL 
SELECT AVG(SAL)
      ,'20' AS DNO
FROM EMP
WHERE DEPTNO =20
UNION ALL 
SELECT AVG(SAL)
      ,'30' AS DNO
FROM EMP
WHERE DEPTNO =30
;

SELECT DEPTNO
      ,JOB 
      ,AVG(SAL + NVL(COMM ,0))
      ,MAX(SAL + NVL(COMM ,0))
      ,MIN(SAL + NVL(COMM ,0)) 
      ,SUM(SAL + NVL(COMM ,0))
      ,COUNT(SAL) 
FROM EMP
GROUP BY DEPTNO
        ,JOB 
ORDER BY DEPTNO
        ,JOB         
;


--JOIN : 테이블 정규화로 분할된 테이블 컬럼을 다시 합치는 작업
SELECT *
FROM EMP A, DEPT B
WHERE A.DEPTNO = B.DEPTNO 
ORDER BY EMPNO 
;


SELECT *
FROM EMP A
INNER JOIN DEPT B
ON A.DEPTNO = B.DEPTNO 
ORDER BY EMPNO 
;

VAR_DEPTNO;

VAR_SQL ="SELECT E.EMPNO
                ,E.HIREDATE 
 		        ,D.DNAME
	    	    ,E.JOB 
                ,E.SAL 
		  FROM EMP E
		  INNER JOIN DEPT D 
		  ON E.{$VAR_DEPTNO} =D.{$VAR_DEPTNO}"
;

SELECT E.EMPNO
      ,E.HIREDATE 
      ,D.DNAME
      ,E.JOB 
      ,E.SAL 
FROM EMP E
INNER JOIN DEPT D 
ON E.DEPTNO =D.DEPTNO 
;


SELECT E.EMPNO 
      ,TO_CHAR(HIREDATE,'YY/MM/DD') AS HIREDATE  
      ,E.ENAME 
      ,D.DEPTNO 
      ,D.LOC 
FROM EMP E
    ,DEPT D
WHERE E.DEPTNO = D.DEPTNO 
ORDER BY D.DEPTNO , E.EMPNO 
;


SELECT D.DNAME 
      ,ROUND(AVG(E.SAL),0) AS AVG_SAL
      ,SUM(E.SAL)
      ,MAX(E.SAL)
      ,MIN(E.SAL)
      ,COUNT(E.SAL) 
FROM EMP E
    ,DEPT D
WHERE E.DEPTNO = D.DEPTNO 
GROUP BY D.DNAME 
;


SELECT e.ENAME 
      ,e.DEPTNO 
      ,s.GRADE 
      ,e.SAL
      ,e.JOB 
FROM EMP e
    ,SALGRADE s 
WHERE E.SAL BETWEEN S.LOSAL AND S.HISAL 
;


SELECT B.GRADE 
      ,COUNT(A.ENAME) AS EMP_CNT 
FROM EMP A
    ,SALGRADE B
WHERE A.SAL BETWEEN B.LOSAL AND B.HISAL 
GROUP BY B.GRADE 
ORDER BY EMP_CNT 
;


SELECT *
FROM EMP A
    ,DEPT B
WHERE A.DEPTNO = B.DEPTNO 
;


--SELF JOIN--
SELECT A.EMPNO 
      ,A.ENAME 
      ,A.MGR 
      ,B.EMPNO AS MGR_EMPNO
      ,B.ENAME AS MGR_ENAME
FROM EMP A
    ,EMP B
WHERE A.MGR = B.EMPNO 
;

--LEFT OUTER JOIN
SELECT A.EMPNO 
      ,A.ENAME 
      ,A.MGR 
      ,B.EMPNO AS MGR_EMPNO
      ,B.ENAME AS MGR_ENAME
FROM EMP A
    ,EMP B
WHERE A.MGR = B.EMPNO (+)
;


SELECT A.EMPNO 
      ,A.ENAME 
      ,A.MGR 
      ,B.EMPNO AS MGR_EMPNO
      ,B.ENAME AS MGR_ENAME
FROM EMP A
LEFT OUTER JOIN EMP B 
ON A.MGR = B.EMPNO 
;

--RIGHT JOIN
SELECT A.EMPNO 
      ,A.ENAME 
      ,A.MGR 
      ,B.EMPNO AS MGR_EMPNO
      ,B.ENAME AS MGR_ENAME
FROM EMP A
    ,EMP B
WHERE A.MGR (+) = B.EMPNO
;

SELECT A.EMPNO 
      ,A.ENAME 
      ,A.MGR 
      ,B.EMPNO AS MGR_EMPNO
      ,B.ENAME AS MGR_ENAME
FROM EMP A
RIGHT OUTER JOIN EMP B
ON A.MGR = B.EMPNO 
;

SELECT A.EMPNO 
      ,A.ENAME 
      ,A.MGR 
      ,B.EMPNO AS MGR_EMPNO
      ,B.ENAME AS MGR_ENAME
FROM EMP A
FULL OUTER JOIN EMP B
ON A.MGR = B.EMPNO 
ORDER BY A.EMPNO  
;

SELECT 
FROM EMP A
FULL OUTER JOIN EMP B


SELECT d.DEPTNO
	  ,d.DNAME
      ,e.ENAME 
      ,e.MGR 
      ,e.SAL
      ,s.LOSAL 
      ,s.HISAL 
      ,s.GRADE 
      ,e2.EMPNO AS MGR_NO
      ,e2.ENAME AS MGR_NAME
FROM EMP e
    ,DEPT d
    ,SALGRADE s 
    ,EMP e2 
WHERE e.DEPTNO  (+) = D.DEPTNO 
AND e.SAL BETWEEN s.LOSAL AND s.HISAL 
AND e.MGR  = e2.EMPNO (+)
;

SELECT d.DEPTNO
	  ,d.DNAME
      ,e.ENAME 
      ,e.MGR 
      ,e.SAL
FROM EMP e
    ,DEPT d
WHERE e.DEPTNO  (+) = D.DEPTNO
;

SELECT e.ENAME 
      ,e.MGR 
      ,e.SAL
      ,s.LOSAL 
      ,s.HISAL 
      ,s.GRADE 
FROM EMP e
    ,SALGRADE s 
WHERE e.SAL BETWEEN s.LOSAL AND s.HISAL
;

SELECT D.DEPTNO
	  ,D.DNAME
      ,E.ENAME 
      ,E.MGR 
      ,E.SAL
      ,S.LOSAL 
      ,S.HISAL 
      ,S.GRADE 
      ,E2.EMPNO AS MGR_NO
      ,E2.ENAME AS MGR_NAME
FROM EMP E
RIGHT OUTER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO 
LEFT OUTER JOIN SALGRADE S 
ON (E.SAL >= S.LOSAL AND E.SAL <=S.HISAL )
LEFT OUTER JOIN EMP E2
ON E.MGR = E2.EMPNO 
;


SELECT *
FROM EMPS
WHERE SAL > (SELECT SAL
             FROM EMP
             WHERE ENAME='BLAKE')
;

SELECT *
FROM EMP E
    ,DEPT D
WHERE E.DEPTNO = D.DEPTNO 
AND E.DEPTNO = 20
AND E.SAL > (SELECT AVG(SAL)
             FROM EMP)
;
   

SELECT DEPTNO, ENAME, SAL
FROM EMP
WHERE SAL IN (SELECT MAX(SAL)
              FROM EMP
              GROUP BY DEPTNO)
;

SELECT DEPTNO, ENAME, SAL
FROM EMP
WHERE SAL = ANY (SELECT MAX(SAL)
                 FROM EMP
                 GROUP BY DEPTNO)
;  

SELECT DEPTNO, ENAME, SAL
FROM EMP
WHERE SAL < ANY (SELECT SAL
                 FROM EMP
                 WHERE DEPTNO = 30)
;

SELECT DEPTNO, ENAME, SAL
FROM EMP
WHERE SAL < ALL (SELECT SAL
                 FROM EMP
                 WHERE DEPTNO = 30)
;

SELECT A.DEPTNO
      ,A.SAL
      ,A.EMPNO
      ,A.ENAME
FROM (SELECT *
      FROM EMP
      WHERE DEPTNO =10) A
     ,(SELECT * 
      FROM DEPT) B
WHERE A.DEPTNO = B.DEPTNO
;


--WITH 절 사용 - 편리한 가상 테이블로 활용`
WITH E AS (SELECT *
           FROM EMP
           WHERE DEPTNO =10),
     D AS (SELECT *
           FROM DEPT),
     S AS (SELECT *
           FROM SALGRADE)      
 SELECT E.EMPNO
       ,E.ENAME
       ,E.DEPTNO
       ,D.DNAME
       ,D.LOC
       ,S.GRADE
 FROM E, D, S
 WHERE E.DEPTNO  = D.DEPTNO
 AND E.SAL BETWEEN S.LOSAL AND HISAL
 ;


CREATE TABLE DEPT_TEMP AS
SELECT *
FROM DEPT
;


