/*
 * TRANSACTION 테스트
 * 
 * 테이블 CREATE -> INSERT -> UPDATE -> DELETE -> ROLLBACK
 */

CREATE TABLE DEPT_TCL AS
SELECT * FROM DEPT ;

SELECT * FROM DEPT_TCL;

INSERT INTO DEPT_TCL
VALUES (50, 'DATABASE', 'SEOUL')
;

UPDATE DEPT_TCL
SET LOC='BUSAN'
WHERE DEPTNO = 40
;

DELETE DEPT_TCL
WHERE DNAME = 'RESEARCH'
;

ROLLBACK;

--COMMIT 실행하는 경우

INSERT INTO DEPT_TCL
VALUES (50, 'NETWORK', 'SEOUL')
;

UPDATE DEPT_TCL
SET LOC='BUSAN'
WHERE DEPTNO = 20
;

DELETE DEPT_TCL
WHERE DEPTNO = 40
;

SELECT * FROM DEPT_TCL;

COMMIT;


/*
 * LOCK테스트
 * 
 * 동일한 계정으로 DBEAVER 세션과 SQLPLUS 세션을 열어
 * 데이터를 수정하는 동시 작업을 수행
 */

UPDATE DEPT_TCL
SET LOC = 'DAEGU'
WHERE DEPTNO = 30
;

/*
 * 튜닝 전과 후 비교
 */
SELECT *
FROM EMP
WHERE SUBSTR(EMPNO,1,2)=75
AND LENGTH(EMPNO) = 4
;


/*
 * 튜닝
*/

--전
SELECT DISTINCT E.EMPNO, E.ENAME , D.DEPTNO 
FROM EMP e 
JOIN DEPT d
ON E.DEPTNO = D.DEPTNO;

--후
SELECT E.EMPNO, E.ENAME , D.DEPTNO 
FROM EMP e 
JOIN DEPT d
ON E.DEPTNO = D.DEPTNO;

--전
SELECT * FROM EMP WHERE DEPTNO =10
UNION
SELECT * FROM EMP WHERE DEPTNO =20;
--후
SELECT * FROM EMP WHERE DEPTNO =10
UNION ALL
SELECT * FROM EMP WHERE DEPTNO =20;


--전
SELECT ENAME, EMPNO, SAL FROM EMP
GROUP BY ENAME , EMPNO 
;

--후
SELECT EMPNO,ENAME, SAL FROM EMP
GROUP BY EMPNO, ENAME 
;

SELECT *
FROM DBA_INDEXES
WHERE TABLE_NAME LIKE 'EMP'
;

DROP INDEX IDX_EMP_JOB;

COMMIT;

CREATE INDEX IDX_EMP_JOB ON EMP(JOB);

SELECT JOB, SUM(SAL) AS SUM_OF_SAL
FROM EMP
GROUP BY JOB
ORDER BY SUM_OF_SAL DESC 
;

SELECT E.EMPLOYEE_ID 
      ,E.JOB_ID
      ,E.DEPARTMENT_ID 
      ,D.LOCATION_ID 
      ,L.COUNTRY_ID 
      ,E.FIRST_NAME 
      ,E.LAST_NAME 
      ,E.SALARY 
      ,E.COMMISSION_PCT 
      ,D.DEPARTMENT_NAME 
      ,J.JOB_TITLE 
      ,L.CITY 
      ,L.STATE_PROVINCE 
      ,C.COUNTRY_NAME 
      ,R.REGION_NAME 
FROM EMPLOYEES E
    ,DEPARTMENTS D
    ,JOBS J
    ,LOCATIONS L
    ,COUNTRIES C
    ,REGIONS R
WHERE E.DEPARTMENT_ID = D.DEPARTMENT_ID 
AND D.LOCATION_ID = L.LOCATION_ID 
AND L.COUNTRY_ID = C.COUNTRY_ID 
AND C.REGION_ID  = R.REGION_ID 
AND J.JOB_ID = E.JOB_ID 
;

/*
 * GROUP BY 구문: 집계 하무를 사용하여 값을 표시
 */

SELECT DEPTNO, FLOOR(AVG(SAL)) AS AVG_SAL
FROM EMP
GROUP BY DEPTNO
;

SELECT * FROM EMP;

SELECT DEPTNO
      ,MAX(DECODE(JOB,'CLECK', SAL)) AS  CLERK
      ,MAX(DECODE(JOB,'SURPRISE', SAL)) AS  SURPRISE
      ,MAX(DECODE(JOB,'SALESMAN', SAL)) AS  SALESMAN
      ,MAX(DECODE(JOB,'MANAGER', SAL)) AS  MANAGER
      ,MAX(DECODE(JOB,'PRESIDENT', SAL)) AS  PRESIDENT
FROM EMP
GROUP BY DEPTNO 
ORDER BY DEPTNO 
;
