/*이론과제 1일차
 * 1. 논리설계, 데이터 모델링
 * 2. E-R모델, E-R모델, Entity
 * 3. E-R Diagram, 관계
 * 4. 카디널리티, 옵셔널리티
 * 5. 스키마, 테이블
 * 6. Table, Index, Sequence
 */


--실습과제 1일차
--(1)--
SELECT EMPNO AS EMPLOYEE_NO
      ,ENAME AS EMPLOYEE_NAME
      ,JOB
      ,MGR AS MANAGER
      ,HIREDATE 
      ,SAL AS SALARY
      ,COMM COMMISSION
      ,DEPTNO AS DEPARMENT_NO
FROM EMP
ORDER BY DEPTNO DESC, ENAME ASC 
;


SELECT EMPNO AS EMPLOYEE_NO
      ,ENAME AS EMPLOYEE_NAME
      ,JOB
      ,MGR AS MANAGER
      ,HIREDATE 
      ,SAL AS SALARY
      ,COMM COMMISSION
      ,DEPTNO AS DEPARMENT_NO
FROM EMP
WHERE COMM IS NULL 
AND SAL IS NOT NULL -- NULL갑과는 비교연산 불가
ORDER BY DEPTNO DESC, ENAME ASC 
;


SELECT EMPNO AS EMPLOYEE_NO
      ,ENAME AS EMPLOYEE_NAME
      ,JOB
      ,MGR AS MANAGER
      ,HIREDATE 
      ,SAL AS SALARY
      ,COMM COMMISSION
      ,DEPTNO AS DEPARMENT_NO
FROM EMP
WHERE COMM IS NULL
AND MGR IS NULL
ORDER BY DEPTNO DESC, ENAME ASC 
;

--(2)--
SELECT *
FROM EMP
WHERE ENAME LIKE '%S'
;

SELECT *
FROM EMP
WHERE JOB = 'SALESMAN'
AND DEPTNO = 30
;

SELECT *
FROM EMP
WHERE DEPTNO IN (20, 30)
AND SAL > 2000
;

SELECT *
FROM EMP
WHERE DEPTNO = 20
AND SAL > 2000
UNION
SELECT *
FROM EMP
WHERE DEPTNO = 30
AND SAL > 2000
;

SELECT *
FROM EMP
WHERE COMM IS NULL 
AND MGR IS NOT NULL 
AND JOB IN ('CLERK', 'MANAGER')
AND SUBSTR(ENAME,2,1) != 'L'
;

--(3)--
SELECT ENAME
	  ,SUBSTR(EMPNO,1,2)||LPAD('*',LENGTH(EMPNO)-2,'*') AS "EMPNO 마스킹 처리"
	  ,SUBSTR(ENAME,1,1)||LPAD('*',LENGTH(ENAME)-1,'*') AS "ENAME 마스킹 처리"
FROM EMP
WHERE LENGTH(ENAME) >= 6
;

SELECT EMPNO 
      ,ENAME 
      ,JOB 
      ,SAL 
      ,SAL/20 AS DAY_PER_SAL
      ,SAL/160 AS HOUR_PER_SAL
FROM EMP
WHERE JOB IN ('CLERK', 'SALESMAN')
ORDER BY SAL
;


SELECT EMPNO 
	  ,ENAME
	  ,TO_CHAR(NEXT_DAY(ADD_MONTHS(HIREDATE,3),'월요일'),'YYYY-MM-DD') AS HIREDATE 
	  ,NVL(TO_CHAR(COMM),'N/A') AS COMM 
FROM EMP
;

SELECT EMPNO 
	  ,ENAME
	  ,MGR 
	  ,CASE WHEN SUBSTR(MGR,1,2) = 75 THEN '5555'
	        WHEN SUBSTR(MGR,1,2) = 76 THEN '6666'
	        WHEN SUBSTR(MGR,1,2) = 77 THEN '7777'
	        WHEN SUBSTR(MGR,1,2) = 78 THEN '8888'
	        WHEN MGR IS NULL THEN '0000'
	        ELSE '9999' END AS CHG_MGR
FROM EMP
;

FROM DUAL
;
