/*이론과제 2일차
 * 1. 테이블, 외래키, NULL
 * 2. 문자셋, 문자셋
 * 3. VARCHAR2, CHAR
 * 4. 제약조건, 기본키, 외래키
 * 5. 무결성, 무결성, 무결성
 * 6. Unique, Not Null, Index
 */


--실습과제 2일차
--(1)--
--1
SELECT DEPTNO
      ,ROUND(AVG(SAL)) AS AVG_SAL
      ,MAX(SAL) AS MAX_SAL
      ,MIN(SAL) AS MIN_SAL
      ,COUNT(EMPNO) AS CNT
FROM EMP
GROUP BY DEPTNO
;

--2
SELECT JOB
      ,COUNT(EMPNO) AS CNT
FROM EMP
GROUP BY JOB
HAVING COUNT(EMPNO) >=3
;

--3
SELECT EXTRACT(YEAR FROM HIREDATE) AS Y
      ,DEPTNO
      ,COUNT(EMPNO) AS CNT
FROM EMP
GROUP BY EXTRACT(YEAR FROM HIREDATE), DEPTNO
ORDER BY EXTRACT(YEAR FROM HIREDATE), DEPTNO
;

--4
SELECT NVL2(COMM,'Y','N') AS EXIST_COMM
      ,COUNT(*) AS CNT
FROM EMP
GROUP BY NVL2(COMM,'Y','N')
;

--5
SELECT DEPTNO
      ,EXTRACT(YEAR FROM HIREDATE) AS HIRE_YEAR
      ,COUNT(EMPNO) AS CNT
      ,MAX(SAL) AS MAX_SAL
      ,SUM(SAL) AS SUM_SAL
      ,AVG(SAL) AS AVG_SAL
FROM EMP
GROUP BY ROLLUP (DEPTNO, EXTRACT(YEAR FROM HIREDATE))
ORDER BY DEPTNO, EXTRACT(YEAR FROM HIREDATE)
;

--(2)--
--1-1
SELECT B.DEPTNO 
      ,B.DNAME 
      ,A.EMPNO 
      ,A.ENAME 
      ,A.SAL 
FROM EMP A
    ,DEPT B
WHERE A.DEPTNO = B.DEPTNO 
AND A.SAL > 2000
ORDER BY B.DEPTNO 
;

--1-2
SELECT B.DEPTNO 
      ,B.DNAME 
      ,A.EMPNO 
      ,A.ENAME 
      ,A.SAL 
FROM EMP A
INNER JOIN DEPT B
ON A.DEPTNO = B.DEPTNO 
WHERE A.SAL > 2000
ORDER BY B.DEPTNO 
;

--2
SELECT DEPTNO 
      ,DEPT.DNAME
      ,ROUND(AVG(SAL)) AS AVG_SAL
      ,MAX(SAL) AS MAX_SAL
      ,MIN(SAL) AS SUM_SAL
      ,COUNT(EMPNO) AS CNT
FROM EMP
NATURAL JOIN DEPT
GROUP BY DEPTNO
        ,DEPT.DNAME 

--3
SELECT D.DEPTNO 
      ,D.DNAME 
      ,E.EMPNO 
      ,E.ENAME 
      ,E.JOB 
      ,E.SAL 
FROM EMP E
RIGHT OUTER JOIN DEPT D
ON E.DEPTNO  = D.DEPTNO
ORDER BY D.DEPTNO 
;

--4
SELECT D.DEPTNO 
      ,D.DNAME 
      ,E.EMPNO 
      ,E.ENAME 
      ,E.JOB 
      ,E.SAL
      ,S.LOSAL 
      ,S.HISAL 
      ,S.GRADE 
      ,M.EMPNO AS MGR_EMPNO
      ,M.ENAME AS MGR_ENAME
FROM EMP E
RIGHT OUTER JOIN DEPT D
ON E.DEPTNO = D.DEPTNO
LEFT OUTER  JOIN SALGRADE S
ON E.SAL BETWEEN S.LOSAL AND S.HISAL 
LEFT OUTER  JOIN EMP M
ON E.MGR  = M.EMPNO 
ORDER BY D.DEPTNO, E.EMPNO 
;

--(3)--
--1
SELECT A.JOB
      ,A.EMPNO 
      ,A.ENAME 
      ,A.SAL 
      ,B.DEPTNO 
      ,B.DNAME 
FROM EMP A
INNER JOIN DEPT B
ON A.DEPTNO = B.DEPTNO 
WHERE A.JOB = (SELECT JOB
   			   FROM EMP
   			   WHERE ENAME='ALLEN')
;

--2
SELECT A.EMPNO 
      ,A.ENAME 
      ,B.DNAME 
      ,A.HIREDATE 
      ,B.LOC 
      ,A.SAL 
      ,S.GRADE 
FROM EMP A
INNER JOIN DEPT B
ON A.DEPTNO = B.DEPTNO 
LEFT OUTER  JOIN SALGRADE S
ON A.SAL BETWEEN S.LOSAL AND S.HISAL 
WHERE SAL > (SELECT AVG(SAL) 
   			 FROM EMP)
ORDER BY A.SAL DESC, HIREDATE DESC
;

--3
SELECT A.EMPNO 
	  ,A.ENAME 
	  ,A.JOB 
	  ,A.DEPTNO 
	  ,B.DNAME 
	  ,B.LOC 
FROM EMP A
INNER JOIN DEPT B
ON A.DEPTNO = B.DEPTNO 
WHERE A.DEPTNO = 10
AND JOB NOT IN (SELECT JOB
  				FROM EMP
  				WHERE DEPTNO = 30)
;

--4
SELECT A.EMPNO 
	  ,A.ENAME 
	  ,A.SAL 
	  ,S.GRADE 
FROM EMP A
LEFT OUTER  JOIN SALGRADE S
ON A.SAL BETWEEN S.LOSAL AND S.HISAL 
WHERE A.SAL > (SELECT MAX(SAL)
 			   FROM EMP
 			   WHERE JOB = 'SALESMAN')
;

--5
SELECT A.EMPNO 
	  ,A.ENAME 
	  ,A.SAL 
	  ,S.GRADE 
FROM EMP A
LEFT OUTER  JOIN SALGRADE S
ON A.SAL BETWEEN S.LOSAL AND S.HISAL 
WHERE A.SAL > ALL (SELECT SAL
 			       FROM EMP
 			       WHERE JOB = 'SALESMAN')
;

